from datetime import datetime
from typing import List, Optional
from sqlmodel import Field, Relationship, SQLModel


class RepositoryAnalysis(SQLModel, table=True):
    """
    Represents an analysis record of a cloned Git repository.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    repo_url: str = Field(index=True)
    repo_name: str
    analyzed_at: datetime = Field(default_factory=datetime.utcnow)
    status: str = Field(default="PENDING")  # PENDING, COMPLETED, FAILED
    error_message: Optional[str] = Field(default=None, nullable=True)

    # Relationship back to suggestions. When an analysis is deleted, delete all child suggestions.
    suggestions: List["ReviewSuggestion"] = Relationship(
        back_populates="analysis", sa_relationship_kwargs={"cascade": "all, delete-orphan"}
    )


class ReviewSuggestion(SQLModel, table=True):
    """
    Represents a specific code improvement recommendation generated by the AI.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    analysis_id: int = Field(foreign_key="repositoryanalysis.id")

    file_path: str
    file_language: str
    line_number: Optional[int] = Field(default=None, nullable=True)
    category: str  # quality, security, optimization, readability
    severity: str  # LOW, MEDIUM, HIGH
    title: str
    description: str
    suggestion_code: Optional[str] = Field(default=None, nullable=True)
    original_code: Optional[str] = Field(default=None, nullable=True)

    # Back-reference relationship mapping
    analysis: RepositoryAnalysis = Relationship(back_populates="suggestions")
